FROM rockylinux:9
RUN dnf -y install --allowerasing \
      rpm-build rpmdevtools rpmlint createrepo_c \
      git tar gzip findutils which python3 systemd-rpm-macros \
 && dnf -y module reset nodejs \
 && dnf -y module enable nodejs:22 \
 && dnf -y install nodejs npm \
 && dnf clean all
WORKDIR /build
