# name        family  image                desktop
el8           rpm     rockylinux:8         yes
el9           rpm     rockylinux:9         yes
el10          rpm     rockylinux/rockylinux:10  yes
amazon2023    rpm     amazonlinux:2023     yes
debian12      deb     debian:12            yes
debian13      deb     debian:13            yes
ubuntu2004    deb     ubuntu:20.04         yes
ubuntu2204    deb     ubuntu:22.04         yes
ubuntu2404    deb     ubuntu:24.04         yes
