#!/usr/bin/env bash
# Build the headless server payload. Produces exactly the tree that is
# installed to /usr/lib/percona-valkey-admin-server.
#
# The apps/ structure is load-bearing: the server bundle resolves its frontend
# as ../../frontend/dist and the collector entry as ../../metrics/dist/index.cjs,
# with no environment override for the frontend path.
set -euo pipefail
SRC="$(cd "$1" && pwd)"
DEST="$2"
BUILD="$(mktemp -d)"
trap 'rm -rf "$BUILD"' EXIT

# Build out of tree so a bind-mounted read-only source stays untouched.
# node_modules/release/dist are excluded: node_modules is regenerated by
# npm ci below (and copying it here would be ~1GB of wasted I/O), and
# release/dist are stale build output that would otherwise shadow what
# this script builds fresh.
tar -c --exclude=node_modules --exclude=release --exclude=dist -C "$SRC" . | tar -x -C "$BUILD"
cd "$BUILD"

# The desktop binary is not needed for the server package.
export ELECTRON_SKIP_BINARY_DOWNLOAD=1
npm ci --no-audit --no-fund
npm run build:common
npm run build:vite:server
npm run build:metrics
npm run build:frontend

mkdir -p "$DEST/apps/server/dist" \
         "$DEST/apps/metrics/dist" \
         "$DEST/apps/frontend" \
         "$DEST/node_modules/@valkey"

cp "$BUILD/apps/server/dist/index.cjs"   "$DEST/apps/server/dist/index.cjs"
cp "$BUILD/apps/metrics/dist/index.cjs"  "$DEST/apps/metrics/dist/index.cjs"
cp "$BUILD/apps/metrics/config.yml"      "$DEST/apps/metrics/config.yml"
cp -a "$BUILD/apps/frontend/dist"        "$DEST/apps/frontend/dist"

# Only the externals the vite bundle does not inline. Everything else is inlined.
for m in ws long protobufjs; do
  cp -a "$BUILD/node_modules/$m" "$DEST/node_modules/$m"
done
cp -a "$BUILD/node_modules/@protobufjs" "$DEST/node_modules/@protobufjs"
cp -a "$BUILD/node_modules/@valkey/valkey-glide" "$DEST/node_modules/@valkey/valkey-glide"

# The native addon matching this build architecture.
case "$(uname -m)" in
  x86_64)        addon=valkey-glide-linux-x64-gnu ;;
  aarch64|arm64) addon=valkey-glide-linux-arm64-gnu ;;
  *) echo "unsupported architecture: $(uname -m)" >&2; exit 1 ;;
esac
cp -a "$BUILD/node_modules/@valkey/$addon" "$DEST/node_modules/@valkey/$addon"

echo "payload built at $DEST"
